############################################################
# +------------------------------------------------------+ #
# |                       NightVision                    | #
# +------------------------------------------------------+ #
############################################################   

EnableMessage: '&8(&c!&8)&7 Night Vision has been Enabled!'

DisableMessage: '&8(&c!&8)&7 Night Vision has been Disabled!'